name: Deploy Voice Memo

on:
  push:
    branches:
      - main
    paths:
      - "application/backend/**"
      - ".github/workflows/app.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      WORKDIR: ./application/backend
      RESGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      APP_PORT: ${{ secrets.APP_PORT }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      DB_IMAGE_NAME: ${{ secrets.DB_IMAGE_NAME }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DATABASE_PATH: ${{ secrets.DATABASE_PATH }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

    steps:
      - name: Code Checkout
        uses: actions/checkout@v6.0.1
        with:
          ssh-key: env.SSH_PRIVATE_KEY
          ssh-strict: env.SSH_HOST
          ssh-user: env.SSH_USER

      - name: Set Version based on (SHA)
        run: echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Login on GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ env.GH_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.WORKDIR }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy through SSH Pipe 
        run: |
          export IMAGE_NAME=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          
          envsubst < ${{ env.WORKDIR }}/docker-compose.yml | ssh ${{ env.SSH_USER }}@${{ env.SSH_HOST }} \
          "docker compose -f - up -d --no-build --remove-orphans"