name: Deploy Voice Memo

on:
  push:
    branches:
      - main
    paths:
      - "application/backend/**"
      - ".github/workflows/backend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      WORKDIR: ./application/backend
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DB_PASSWORD:  ${{ secrets.DB_PASSWORD }}
      API_KEY: ${{ secrets.API_KEY }}
      MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
      MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      MAIL_USER: ${{ secrets.MAIL_USER }}
      MAIL_HOST: ${{ secrets.MAIL_HOST }}
      MAIL_PASS: ${{ secrets.MAIL_PASS }}
      OBS_EMAIL: ${{ secrets.OBS_EMAIL }}
      OBS_PASSWORD: ${{ secrets.OBS_PASSWORD }}
      OTLP_AUTH_HEADER: ${{ secrets.OTLP_AUTH_HEADER }}
      CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Code Checkout
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0

      - name: Set Version based on (SHA)
        run: echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # - name: Secret Scanning (Gitleaks)
      #   uses: gitleaks/gitleaks-action@v2
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ env.WORKDIR }}/Dockerfile
          failure-threshold: warning

      - name: NPM Audit
        run: |
          cd ${{ env.WORKDIR }}
          npm audit --audit-level=critical

      - name: Set SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login on GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ env.GH_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.WORKDIR }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Build and Push Migrator
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.WORKDIR }}
          push: true
          target: build
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:migrator

      - name: Deploy through SSH Pipe 
        run: |
          export IMAGE_NAME=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          
          # Docker and VPS login
          echo "${{ env.GH_TOKEN }}" | ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.SSH_HOST }} \
          "docker login ghcr.io -u ${{ github.actor }} --password-stdin"
          
          envsubst < ${{ env.WORKDIR }}/docker-compose.yml | ssh ${{ env.SSH_USER }}@${{ env.SSH_HOST }} \
          "docker compose -p backend-voice-memo -f - up -d --no-build --remove-orphans --force-recreate"

      - name: Clean old images
        uses: snok/container-retention-policy@v3.0.1
        with:
          image-names: voice-memo
          cut-off: 5m
          keep-at-least: 2
          account: athena-devs
          token: ${{ secrets.GITHUB_TOKEN }}
  
  security-audit:
    needs: deploy
    if: success()
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    env:
      REGISTRY: ghcr.io
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Code Checkout
        uses: actions/checkout@v6.0.1

      - name: Set Version based on (SHA)
        run: echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login to Docker Hub (Required for Scout)
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PAT }}

      - name: Login on GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ env.GITHUB_TOKEN }}

      - name: Docker Scout Quickview
        uses: docker/scout-action@v1
        with:
          command: quickview
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.SHA }}

      - name: Docker Scout CVEs
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.SHA }}
          ignore-unchanged: true
          only-severities: critical,high
          write-comment: true