name: Deploy Voice Memo

on:
  push:
    branches:
      - main
    paths:
      - "application/backend/**"
      - ".github/workflows/backend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      WORKDIR: ./application/backend
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      APP_PORT: ${{ secrets.APP_PORT }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      DB_IMAGE_NAME: ${{ secrets.DB_IMAGE_NAME }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DATABASE_PATH: ${{ secrets.DATABASE_PATH }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }} 
      API_KEY: ${{ secrets.API_KEY }}
      MINIO_FIRST_PORT: ${{ secrets.MINIO_FIRST_PORT }}
      MINIO_SECONDARY_PORT: ${{ secrets.MINIO_SECONDARY_PORT }}
      MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
      MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
      CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
      JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
      SALT_RESULT: ${{ secrets.SALT_RESULT }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Code Checkout
        uses: actions/checkout@v6.0.1

      - name: Set Version based on (SHA)
        run: echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Login on GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ env.GH_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.WORKDIR }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy through SSH Pipe 
        run: |
          export IMAGE_NAME=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          
          # Docker and VPS login
          echo "${{ env.GH_TOKEN }}" | ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.SSH_HOST }} \
          "docker login ghcr.io -u ${{ github.actor }} --password-stdin"
          
          envsubst < ${{ env.WORKDIR }}/docker-compose.yml | ssh ${{ env.SSH_USER }}@${{ env.SSH_HOST }} \
          "docker compose -f - up -d --no-build --remove-orphans --force-recreate"

      - name: Clean old images
        uses: snok/container-retention-policy@v3.0.1
        with:
          image-names: voice-memo
          cut-off: 5m
          keep-at-least: 2
          account: athena-devs
          token: ${{ secrets.GITHUB_TOKEN }}
